#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4{1,0,4.9,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g.dep
package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g: package/package_ti.runtime.wiring.cc32xx.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.sm4g: package/package_ti.runtime.wiring.cc32xx.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../IPAddress.om4g.dep
package/lib/lib/wiring_cc32xx/../IPAddress.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../IPAddress.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../IPAddress.om4g: ../IPAddress.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../IPAddress.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../IPAddress.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../IPAddress.sm4g: ../IPAddress.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../IPAddress.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../MACAddress.om4g.dep
package/lib/lib/wiring_cc32xx/../MACAddress.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../MACAddress.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../MACAddress.om4g: ../MACAddress.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../MACAddress.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../MACAddress.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../MACAddress.sm4g: ../MACAddress.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../MACAddress.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../PrintD.om4g.dep
package/lib/lib/wiring_cc32xx/../PrintD.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../PrintD.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../PrintD.om4g: ../PrintD.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../PrintD.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../PrintD.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../PrintD.sm4g: ../PrintD.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../PrintD.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../new.om4g.dep
package/lib/lib/wiring_cc32xx/../new.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../new.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../new.om4g: ../new.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../new.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../new.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../new.sm4g: ../new.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../new.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../WMath.om4g.dep
package/lib/lib/wiring_cc32xx/../WMath.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../WMath.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WMath.om4g: ../WMath.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WMath.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../WMath.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WMath.sm4g: ../WMath.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WMath.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../WString.om4g.dep
package/lib/lib/wiring_cc32xx/../WString.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../WString.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WString.om4g: ../WString.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WString.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../WString.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WString.sm4g: ../WString.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WString.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../WStringD.om4g.dep
package/lib/lib/wiring_cc32xx/../WStringD.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../WStringD.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WStringD.om4g: ../WStringD.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WStringD.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../WStringD.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WStringD.sm4g: ../WStringD.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WStringD.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../Wire.om4g.dep
package/lib/lib/wiring_cc32xx/../Wire.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../Wire.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Wire.om4g: ../Wire.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Wire.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../Wire.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Wire.sm4g: ../Wire.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Wire.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../SPI.om4g.dep
package/lib/lib/wiring_cc32xx/../SPI.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../SPI.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../SPI.om4g: ../SPI.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../SPI.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../SPI.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../SPI.sm4g: ../SPI.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../SPI.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../PString.om4g.dep
package/lib/lib/wiring_cc32xx/../PString.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../PString.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../PString.om4g: ../PString.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../PString.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../PString.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../PString.sm4g: ../PString.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../PString.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../Tone.om4g.dep
package/lib/lib/wiring_cc32xx/../Tone.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../Tone.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Tone.om4g: ../Tone.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Tone.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../Tone.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Tone.sm4g: ../Tone.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Tone.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../Stream.om4g.dep
package/lib/lib/wiring_cc32xx/../Stream.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../Stream.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Stream.om4g: ../Stream.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Stream.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../Stream.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Stream.sm4g: ../Stream.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Stream.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../Print.om4g.dep
package/lib/lib/wiring_cc32xx/../Print.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../Print.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Print.om4g: ../Print.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Print.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../Print.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../Print.sm4g: ../Print.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../Print.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../PStringD.om4g.dep
package/lib/lib/wiring_cc32xx/../PStringD.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../PStringD.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../PStringD.om4g: ../PStringD.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../PStringD.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../PStringD.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../PStringD.sm4g: ../PStringD.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../PStringD.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g.dep
package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g: ../HardwareSerial.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../HardwareSerial.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../HardwareSerial.sm4g: ../HardwareSerial.cpp lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../HardwareSerial.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/./wiring_analog.om4g.dep
package/lib/lib/wiring_cc32xx/./wiring_analog.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/./wiring_analog.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/./wiring_analog.om4g: ./wiring_analog.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/./wiring_analog.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/./wiring_analog.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/./wiring_analog.sm4g: ./wiring_analog.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/./wiring_analog.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/./wiring.om4g.dep
package/lib/lib/wiring_cc32xx/./wiring.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/./wiring.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/./wiring.om4g: ./wiring.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/./wiring.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/./wiring.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/./wiring.sm4g: ./wiring.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/./wiring.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../WInterrupts.om4g.dep
package/lib/lib/wiring_cc32xx/../WInterrupts.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../WInterrupts.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WInterrupts.om4g: ../WInterrupts.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WInterrupts.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../WInterrupts.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../WInterrupts.sm4g: ../WInterrupts.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../WInterrupts.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../itoa.om4g.dep
package/lib/lib/wiring_cc32xx/../itoa.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../itoa.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../itoa.om4g: ../itoa.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../itoa.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../itoa.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../itoa.sm4g: ../itoa.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../itoa.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../random.om4g.dep
package/lib/lib/wiring_cc32xx/../random.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../random.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../random.om4g: ../random.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../random.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../random.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../random.sm4g: ../random.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../random.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g.dep
package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g: ../wiring_pulse.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../wiring_pulse.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../wiring_pulse.sm4g: ../wiring_pulse.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../wiring_pulse.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../wiring_shift.om4g.dep
package/lib/lib/wiring_cc32xx/../wiring_shift.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../wiring_shift.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../wiring_shift.om4g: ../wiring_shift.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../wiring_shift.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../wiring_shift.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../wiring_shift.sm4g: ../wiring_shift.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../wiring_shift.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../wiring_digital.om4g.dep
package/lib/lib/wiring_cc32xx/../wiring_digital.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../wiring_digital.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../wiring_digital.om4g: ../wiring_digital.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../wiring_digital.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../wiring_digital.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../wiring_digital.sm4g: ../wiring_digital.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../wiring_digital.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g.dep
package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g.dep: ;
endif

package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g: | .interfaces
package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g: ../avr/dtostrf.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g: export LD_LIBRARY_PATH=

package/lib/lib/wiring_cc32xx/../avr/dtostrf.sm4g: | .interfaces
package/lib/lib/wiring_cc32xx/../avr/dtostrf.sm4g: ../avr/dtostrf.c lib/wiring_cc32xx.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -D_POSIX_SOURCE -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/wiring_cc32xx/../avr/dtostrf.sm4g: export LD_LIBRARY_PATH=

clean,m4g ::
	-$(RM) package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../IPAddress.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../MACAddress.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../PrintD.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../new.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WMath.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WString.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WStringD.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Wire.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../SPI.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../PString.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Tone.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Stream.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Print.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../PStringD.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/./wiring_analog.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/./wiring.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WInterrupts.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../itoa.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../random.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../wiring_shift.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../wiring_digital.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g
	-$(RM) package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../IPAddress.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../MACAddress.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../PrintD.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../new.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WMath.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WString.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WStringD.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Wire.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../SPI.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../PString.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Tone.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Stream.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../Print.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../PStringD.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../HardwareSerial.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/./wiring_analog.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/./wiring.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../WInterrupts.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../itoa.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../random.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../wiring_pulse.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../wiring_shift.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../wiring_digital.sm4g
	-$(RM) package/lib/lib/wiring_cc32xx/../avr/dtostrf.sm4g

lib/wiring_cc32xx.m4g.lib: package/lib/lib/wiring_cc32xx/package/package_ti.runtime.wiring.cc32xx.om4g package/lib/lib/wiring_cc32xx/../IPAddress.om4g package/lib/lib/wiring_cc32xx/../MACAddress.om4g package/lib/lib/wiring_cc32xx/../PrintD.om4g package/lib/lib/wiring_cc32xx/../new.om4g package/lib/lib/wiring_cc32xx/../WMath.om4g package/lib/lib/wiring_cc32xx/../WString.om4g package/lib/lib/wiring_cc32xx/../WStringD.om4g package/lib/lib/wiring_cc32xx/../Wire.om4g package/lib/lib/wiring_cc32xx/../SPI.om4g package/lib/lib/wiring_cc32xx/../PString.om4g package/lib/lib/wiring_cc32xx/../Tone.om4g package/lib/lib/wiring_cc32xx/../Stream.om4g package/lib/lib/wiring_cc32xx/../Print.om4g package/lib/lib/wiring_cc32xx/../PStringD.om4g package/lib/lib/wiring_cc32xx/../HardwareSerial.om4g package/lib/lib/wiring_cc32xx/./wiring_analog.om4g package/lib/lib/wiring_cc32xx/./wiring.om4g package/lib/lib/wiring_cc32xx/../WInterrupts.om4g package/lib/lib/wiring_cc32xx/../itoa.om4g package/lib/lib/wiring_cc32xx/../random.om4g package/lib/lib/wiring_cc32xx/../wiring_pulse.om4g package/lib/lib/wiring_cc32xx/../wiring_shift.om4g package/lib/lib/wiring_cc32xx/../wiring_digital.om4g package/lib/lib/wiring_cc32xx/../avr/dtostrf.om4g lib/wiring_cc32xx.m4g.lib.mak

clean::
	-$(RM) lib/wiring_cc32xx.m4g.lib.mak
