#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4{1,0,4.9,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g.dep
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g.dep: ;
endif

package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g: package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.c lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g: export LD_LIBRARY_PATH=

package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sm4g: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sm4g: package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.c lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SerialObjects.om4g.dep
package/lib/lib/board/./SerialObjects.om4g.dep: ;
endif

package/lib/lib/board/./SerialObjects.om4g: | .interfaces
package/lib/lib/board/./SerialObjects.om4g: ./SerialObjects.cpp lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.om4g: export LD_LIBRARY_PATH=

package/lib/lib/board/./SerialObjects.sm4g: | .interfaces
package/lib/lib/board/./SerialObjects.sm4g: ./SerialObjects.cpp lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SpiObjects.om4g.dep
package/lib/lib/board/./SpiObjects.om4g.dep: ;
endif

package/lib/lib/board/./SpiObjects.om4g: | .interfaces
package/lib/lib/board/./SpiObjects.om4g: ./SpiObjects.cpp lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.om4g: export LD_LIBRARY_PATH=

package/lib/lib/board/./SpiObjects.sm4g: | .interfaces
package/lib/lib/board/./SpiObjects.sm4g: ./SpiObjects.cpp lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./WireObjects.om4g.dep
package/lib/lib/board/./WireObjects.om4g.dep: ;
endif

package/lib/lib/board/./WireObjects.om4g: | .interfaces
package/lib/lib/board/./WireObjects.om4g: ./WireObjects.cpp lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.om4g: export LD_LIBRARY_PATH=

package/lib/lib/board/./WireObjects.sm4g: | .interfaces
package/lib/lib/board/./WireObjects.sm4g: ./WireObjects.cpp lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./Board_init.om4g.dep
package/lib/lib/board/./Board_init.om4g.dep: ;
endif

package/lib/lib/board/./Board_init.om4g: | .interfaces
package/lib/lib/board/./Board_init.om4g: ./Board_init.c lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.om4g: export LD_LIBRARY_PATH=

package/lib/lib/board/./Board_init.sm4g: | .interfaces
package/lib/lib/board/./Board_init.sm4g: ./Board_init.c lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./pins.om4g.dep
package/lib/lib/board/./pins.om4g.dep: ;
endif

package/lib/lib/board/./pins.om4g: | .interfaces
package/lib/lib/board/./pins.om4g: ./pins.c lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.om4g: export LD_LIBRARY_PATH=

package/lib/lib/board/./pins.sm4g: | .interfaces
package/lib/lib/board/./pins.sm4g: ./pins.c lib/board.m4g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.sm4g: export LD_LIBRARY_PATH=

clean,m4g ::
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g
	-$(RM) package/lib/lib/board/./SerialObjects.om4g
	-$(RM) package/lib/lib/board/./SpiObjects.om4g
	-$(RM) package/lib/lib/board/./WireObjects.om4g
	-$(RM) package/lib/lib/board/./Board_init.om4g
	-$(RM) package/lib/lib/board/./pins.om4g
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sm4g
	-$(RM) package/lib/lib/board/./SerialObjects.sm4g
	-$(RM) package/lib/lib/board/./SpiObjects.sm4g
	-$(RM) package/lib/lib/board/./WireObjects.sm4g
	-$(RM) package/lib/lib/board/./Board_init.sm4g
	-$(RM) package/lib/lib/board/./pins.sm4g

lib/board.m4g.lib: package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.om4g package/lib/lib/board/./SerialObjects.om4g package/lib/lib/board/./SpiObjects.om4g package/lib/lib/board/./WireObjects.om4g package/lib/lib/board/./Board_init.om4g package/lib/lib/board/./pins.om4g lib/board.m4g.lib.mak

clean::
	-$(RM) lib/board.m4g.lib.mak
