#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,16.9,0
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4.dep
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4.dep: ;
endif

package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4: package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.c lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/package -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4: export C_DIR=
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sem4: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sem4: package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.c lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/package -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sem4: export C_DIR=
package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SerialObjects.oem4.dep
package/lib/lib/board/./SerialObjects.oem4.dep: ;
endif

package/lib/lib/board/./SerialObjects.oem4: | .interfaces
package/lib/lib/board/./SerialObjects.oem4: ./SerialObjects.cpp lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.oem4: export C_DIR=
package/lib/lib/board/./SerialObjects.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/board/./SerialObjects.sem4: | .interfaces
package/lib/lib/board/./SerialObjects.sem4: ./SerialObjects.cpp lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.sem4: export C_DIR=
package/lib/lib/board/./SerialObjects.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SpiObjects.oem4.dep
package/lib/lib/board/./SpiObjects.oem4.dep: ;
endif

package/lib/lib/board/./SpiObjects.oem4: | .interfaces
package/lib/lib/board/./SpiObjects.oem4: ./SpiObjects.cpp lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.oem4: export C_DIR=
package/lib/lib/board/./SpiObjects.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/board/./SpiObjects.sem4: | .interfaces
package/lib/lib/board/./SpiObjects.sem4: ./SpiObjects.cpp lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.sem4: export C_DIR=
package/lib/lib/board/./SpiObjects.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./WireObjects.oem4.dep
package/lib/lib/board/./WireObjects.oem4.dep: ;
endif

package/lib/lib/board/./WireObjects.oem4: | .interfaces
package/lib/lib/board/./WireObjects.oem4: ./WireObjects.cpp lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.oem4: export C_DIR=
package/lib/lib/board/./WireObjects.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/board/./WireObjects.sem4: | .interfaces
package/lib/lib/board/./WireObjects.sem4: ./WireObjects.cpp lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.sem4: export C_DIR=
package/lib/lib/board/./WireObjects.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./Board_init.oem4.dep
package/lib/lib/board/./Board_init.oem4.dep: ;
endif

package/lib/lib/board/./Board_init.oem4: | .interfaces
package/lib/lib/board/./Board_init.oem4: ./Board_init.c lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.oem4: export C_DIR=
package/lib/lib/board/./Board_init.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/board/./Board_init.sem4: | .interfaces
package/lib/lib/board/./Board_init.sem4: ./Board_init.c lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.sem4: export C_DIR=
package/lib/lib/board/./Board_init.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./pins.oem4.dep
package/lib/lib/board/./pins.oem4.dep: ;
endif

package/lib/lib/board/./pins.oem4: | .interfaces
package/lib/lib/board/./pins.oem4: ./pins.c lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.oem4: export C_DIR=
package/lib/lib/board/./pins.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/board/./pins.sem4: | .interfaces
package/lib/lib/board/./pins.sem4: ./pins.c lib/board.em4.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc"  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.sem4: export C_DIR=
package/lib/lib/board/./pins.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 ::
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4
	-$(RM) package/lib/lib/board/./SerialObjects.oem4
	-$(RM) package/lib/lib/board/./SpiObjects.oem4
	-$(RM) package/lib/lib/board/./WireObjects.oem4
	-$(RM) package/lib/lib/board/./Board_init.oem4
	-$(RM) package/lib/lib/board/./pins.oem4
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.sem4
	-$(RM) package/lib/lib/board/./SerialObjects.sem4
	-$(RM) package/lib/lib/board/./SpiObjects.sem4
	-$(RM) package/lib/lib/board/./WireObjects.sem4
	-$(RM) package/lib/lib/board/./Board_init.sem4
	-$(RM) package/lib/lib/board/./pins.sem4

lib/board.em4.lib: package/lib/lib/board/package/package_ti.runtime.wiring.cc32xx.variants.CC3220SF_LAUNCHXL.oem4 package/lib/lib/board/./SerialObjects.oem4 package/lib/lib/board/./SpiObjects.oem4 package/lib/lib/board/./WireObjects.oem4 package/lib/lib/board/./Board_init.oem4 package/lib/lib/board/./pins.oem4 lib/board.em4.lib.mak

clean::
	-$(RM) lib/board.em4.lib.mak
