#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4F{1,0,16.9,0
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f.dep
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f.dep: ;
endif

package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f: package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.c lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4f $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/package -s oem4f $< -C   -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f: export C_DIR=
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sem4f: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sem4f: package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.c lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4f -n $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/package -s oem4f $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/package -fr=./package/lib/lib/board/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sem4f: export C_DIR=
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SerialObjects.oem4f.dep
package/lib/lib/board/./SerialObjects.oem4f.dep: ;
endif

package/lib/lib/board/./SerialObjects.oem4f: | .interfaces
package/lib/lib/board/./SerialObjects.oem4f: ./SerialObjects.cpp lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4f $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C   -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.oem4f: export C_DIR=
package/lib/lib/board/./SerialObjects.oem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

package/lib/lib/board/./SerialObjects.sem4f: | .interfaces
package/lib/lib/board/./SerialObjects.sem4f: ./SerialObjects.cpp lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4f -n $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.sem4f: export C_DIR=
package/lib/lib/board/./SerialObjects.sem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SpiObjects.oem4f.dep
package/lib/lib/board/./SpiObjects.oem4f.dep: ;
endif

package/lib/lib/board/./SpiObjects.oem4f: | .interfaces
package/lib/lib/board/./SpiObjects.oem4f: ./SpiObjects.cpp lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4f $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C   -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.oem4f: export C_DIR=
package/lib/lib/board/./SpiObjects.oem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

package/lib/lib/board/./SpiObjects.sem4f: | .interfaces
package/lib/lib/board/./SpiObjects.sem4f: ./SpiObjects.cpp lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4f -n $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.sem4f: export C_DIR=
package/lib/lib/board/./SpiObjects.sem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./WireObjects.oem4f.dep
package/lib/lib/board/./WireObjects.oem4f.dep: ;
endif

package/lib/lib/board/./WireObjects.oem4f: | .interfaces
package/lib/lib/board/./WireObjects.oem4f: ./WireObjects.cpp lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4f $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C   -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.oem4f: export C_DIR=
package/lib/lib/board/./WireObjects.oem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

package/lib/lib/board/./WireObjects.sem4f: | .interfaces
package/lib/lib/board/./WireObjects.sem4f: ./WireObjects.cpp lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppem4f -n $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fp $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.sem4f: export C_DIR=
package/lib/lib/board/./WireObjects.sem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./Board_init.oem4f.dep
package/lib/lib/board/./Board_init.oem4f.dep: ;
endif

package/lib/lib/board/./Board_init.oem4f: | .interfaces
package/lib/lib/board/./Board_init.oem4f: ./Board_init.c lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4f $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C   -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.oem4f: export C_DIR=
package/lib/lib/board/./Board_init.oem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

package/lib/lib/board/./Board_init.sem4f: | .interfaces
package/lib/lib/board/./Board_init.sem4f: ./Board_init.c lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4f -n $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.sem4f: export C_DIR=
package/lib/lib/board/./Board_init.sem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./pins.oem4f.dep
package/lib/lib/board/./pins.oem4f.dep: ;
endif

package/lib/lib/board/./pins.oem4f: | .interfaces
package/lib/lib/board/./pins.oem4f: ./pins.c lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4f $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C   -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.oem4f: export C_DIR=
package/lib/lib/board/./pins.oem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

package/lib/lib/board/./pins.sem4f: | .interfaces
package/lib/lib/board/./pins.sem4f: ./pins.c lib/board.em4f.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4f -n $< ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/. -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/board/. -s oem4f $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --abi=eabi --float_support=fpv4spd16 -eo.oem4f -ea.sem4f  -ms --relaxed_ansi --display_error_number  -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2 --gcc --diag_warning=225 -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I$(ti.targets.arm.elf.M4F.rootDir)/include  -fs=./package/lib/lib/board/. -fr=./package/lib/lib/board/.
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.sem4f: export C_DIR=
package/lib/lib/board/./pins.sem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

clean,em4f ::
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f
	-$(RM) package/lib/lib/board/./SerialObjects.oem4f
	-$(RM) package/lib/lib/board/./SpiObjects.oem4f
	-$(RM) package/lib/lib/board/./WireObjects.oem4f
	-$(RM) package/lib/lib/board/./Board_init.oem4f
	-$(RM) package/lib/lib/board/./pins.oem4f
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sem4f
	-$(RM) package/lib/lib/board/./SerialObjects.sem4f
	-$(RM) package/lib/lib/board/./SpiObjects.sem4f
	-$(RM) package/lib/lib/board/./WireObjects.sem4f
	-$(RM) package/lib/lib/board/./Board_init.sem4f
	-$(RM) package/lib/lib/board/./pins.sem4f

lib/board.em4f.lib: package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.oem4f package/lib/lib/board/./SerialObjects.oem4f package/lib/lib/board/./SpiObjects.oem4f package/lib/lib/board/./WireObjects.oem4f package/lib/lib/board/./Board_init.oem4f package/lib/lib/board/./pins.oem4f lib/board.em4f.lib.mak

clean::
	-$(RM) lib/board.em4f.lib.mak
