#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4F{1,0,6.3,1
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg.dep
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg.dep: ;
endif

package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg: package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.c lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sm4fg: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sm4fg: package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.c lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SerialObjects.om4fg.dep
package/lib/lib/board/./SerialObjects.om4fg.dep: ;
endif

package/lib/lib/board/./SerialObjects.om4fg: | .interfaces
package/lib/lib/board/./SerialObjects.om4fg: ./SerialObjects.cpp lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/board/./SerialObjects.sm4fg: | .interfaces
package/lib/lib/board/./SerialObjects.sm4fg: ./SerialObjects.cpp lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SerialObjects.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./SpiObjects.om4fg.dep
package/lib/lib/board/./SpiObjects.om4fg.dep: ;
endif

package/lib/lib/board/./SpiObjects.om4fg: | .interfaces
package/lib/lib/board/./SpiObjects.om4fg: ./SpiObjects.cpp lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/board/./SpiObjects.sm4fg: | .interfaces
package/lib/lib/board/./SpiObjects.sm4fg: ./SpiObjects.cpp lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./SpiObjects.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./WireObjects.om4fg.dep
package/lib/lib/board/./WireObjects.om4fg.dep: ;
endif

package/lib/lib/board/./WireObjects.om4fg: | .interfaces
package/lib/lib/board/./WireObjects.om4fg: ./WireObjects.cpp lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/board/./WireObjects.sm4fg: | .interfaces
package/lib/lib/board/./WireObjects.sm4fg: ./WireObjects.cpp lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./WireObjects.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./Board_init.om4fg.dep
package/lib/lib/board/./Board_init.om4fg.dep: ;
endif

package/lib/lib/board/./Board_init.om4fg: | .interfaces
package/lib/lib/board/./Board_init.om4fg: ./Board_init.c lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/board/./Board_init.sm4fg: | .interfaces
package/lib/lib/board/./Board_init.sm4fg: ./Board_init.c lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./pins.om4fg.dep
package/lib/lib/board/./pins.om4fg.dep: ;
endif

package/lib/lib/board/./pins.om4fg: | .interfaces
package/lib/lib/board/./pins.om4fg: ./pins.c lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/board/./pins.sm4fg: | .interfaces
package/lib/lib/board/./pins.sm4fg: ./pins.c lib/board.m4fg.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DDeviceFamily_MSP432E4 -D__MSP432E401Y__  -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_6_3_1  -Os   -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/inc" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/../../../third_party/CMSIS/Include" -I"/home/xlibrary/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/source/ti/devices/msp432e4/driverlib/MSP432E4xx"  $(XDCINCS) -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/db/vtree/library/trees/mcpi/mcpi-3.35.00.10_eng/exports/coresdk_msp432e4_3_35_00_10_eng/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.sm4fg: export LD_LIBRARY_PATH=

clean,m4fg ::
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg
	-$(RM) package/lib/lib/board/./SerialObjects.om4fg
	-$(RM) package/lib/lib/board/./SpiObjects.om4fg
	-$(RM) package/lib/lib/board/./WireObjects.om4fg
	-$(RM) package/lib/lib/board/./Board_init.om4fg
	-$(RM) package/lib/lib/board/./pins.om4fg
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.sm4fg
	-$(RM) package/lib/lib/board/./SerialObjects.sm4fg
	-$(RM) package/lib/lib/board/./SpiObjects.sm4fg
	-$(RM) package/lib/lib/board/./WireObjects.sm4fg
	-$(RM) package/lib/lib/board/./Board_init.sm4fg
	-$(RM) package/lib/lib/board/./pins.sm4fg

lib/board.m4fg.lib: package/lib/lib/board/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.om4fg package/lib/lib/board/./SerialObjects.om4fg package/lib/lib/board/./SpiObjects.om4fg package/lib/lib/board/./WireObjects.om4fg package/lib/lib/board/./Board_init.om4fg package/lib/lib/board/./pins.om4fg lib/board.m4fg.lib.mak

clean::
	-$(RM) lib/board.m4fg.lib.mak
