#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M3{1,0,4.8,4
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g.dep
package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g.dep: ;
endif

package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g: package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.c lib/board.m3g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -Dgcc=1 -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -I/db/vtree/library/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/products/bios_6_45_01_29/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/driverlib" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g: export LD_LIBRARY_PATH=

package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.sm3g: | .interfaces
package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.sm3g: package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.c lib/board.m3g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -Dgcc=1 -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/driverlib" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./Board_init.om3g.dep
package/lib/lib/board/./Board_init.om3g.dep: ;
endif

package/lib/lib/board/./Board_init.om3g: | .interfaces
package/lib/lib/board/./Board_init.om3g: ./Board_init.c lib/board.m3g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -Dgcc=1 -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os   -I/db/vtree/library/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/products/bios_6_45_01_29/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/driverlib" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.om3g: export LD_LIBRARY_PATH=

package/lib/lib/board/./Board_init.sm3g: | .interfaces
package/lib/lib/board/./Board_init.sm3g: ./Board_init.c lib/board.m3g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -Dgcc=1 -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os   -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/driverlib" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./Board_init.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/board/./pins.om3g.dep
package/lib/lib/board/./pins.om3g.dep: ;
endif

package/lib/lib/board/./pins.om3g: | .interfaces
package/lib/lib/board/./pins.om3g: ./pins.c lib/board.m3g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -Dgcc=1 -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os   -I/db/vtree/library/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/products/bios_6_45_01_29/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/driverlib" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.om3g: export LD_LIBRARY_PATH=

package/lib/lib/board/./pins.sm3g: | .interfaces
package/lib/lib/board/./pins.sm3g: ./pins.c lib/board.m3g.lib.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -Dgcc=1 -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os   -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/driverlib" -I"/home/xlibrary/trees/zumaprod/zumaprod-j08/exports/tirtos_full_2_16_00_08/packages/../products/cc26xxware_2_23_01_16780/inc"  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/board/./pins.sm3g: export LD_LIBRARY_PATH=

clean,m3g ::
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g
	-$(RM) package/lib/lib/board/./Board_init.om3g
	-$(RM) package/lib/lib/board/./pins.om3g
	-$(RM) package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.sm3g
	-$(RM) package/lib/lib/board/./Board_init.sm3g
	-$(RM) package/lib/lib/board/./pins.sm3g

lib/board.m3g.lib: package/lib/lib/board/package/package_ti.runtime.wiring.cc26xx.variants.CC2650_LAUNCHXL.om3g package/lib/lib/board/./Board_init.om3g package/lib/lib/board/./pins.om3g lib/board.m3g.lib.mak

clean::
	-$(RM) lib/board.m3g.lib.mak
