#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4F{1,0,4.9,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg.dep
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg.dep: ;
endif

package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg: | .interfaces
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg: package/package_ti.runtime.wiring.cc32xx.tests.alan.c lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4fg: | .interfaces
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4fg: package/package_ti.runtime.wiring.cc32xx.tests.alan.c lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/GLCDI2C.om4fg.dep
package/lib/lib/sketches/GLCDI2C.om4fg.dep: ;
endif

package/lib/lib/sketches/GLCDI2C.om4fg: | .interfaces
package/lib/lib/sketches/GLCDI2C.om4fg: GLCDI2C.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/GLCDI2C.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/GLCDI2C.sm4fg: | .interfaces
package/lib/lib/sketches/GLCDI2C.sm4fg: GLCDI2C.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/GLCDI2C.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/mon.om4fg.dep
package/lib/lib/sketches/mon.om4fg.dep: ;
endif

package/lib/lib/sketches/mon.om4fg: | .interfaces
package/lib/lib/sketches/mon.om4fg: mon.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/mon.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/mon.sm4fg: | .interfaces
package/lib/lib/sketches/mon.sm4fg: mon.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/mon.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/monitor1.om4fg.dep
package/lib/lib/sketches/monitor1.om4fg.dep: ;
endif

package/lib/lib/sketches/monitor1.om4fg: | .interfaces
package/lib/lib/sketches/monitor1.om4fg: monitor1.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor1.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/monitor1.sm4fg: | .interfaces
package/lib/lib/sketches/monitor1.sm4fg: monitor1.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor1.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/monitor.om4fg.dep
package/lib/lib/sketches/monitor.om4fg.dep: ;
endif

package/lib/lib/sketches/monitor.om4fg: | .interfaces
package/lib/lib/sketches/monitor.om4fg: monitor.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/monitor.sm4fg: | .interfaces
package/lib/lib/sketches/monitor.sm4fg: monitor.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch0.om4fg.dep
package/lib/lib/sketches/sketch0.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch0.om4fg: | .interfaces
package/lib/lib/sketches/sketch0.om4fg: sketch0.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch0.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch0.sm4fg: | .interfaces
package/lib/lib/sketches/sketch0.sm4fg: sketch0.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch0.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch1.om4fg.dep
package/lib/lib/sketches/sketch1.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch1.om4fg: | .interfaces
package/lib/lib/sketches/sketch1.om4fg: sketch1.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch1.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch1.sm4fg: | .interfaces
package/lib/lib/sketches/sketch1.sm4fg: sketch1.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch1.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch2.om4fg.dep
package/lib/lib/sketches/sketch2.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch2.om4fg: | .interfaces
package/lib/lib/sketches/sketch2.om4fg: sketch2.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch2.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch2.sm4fg: | .interfaces
package/lib/lib/sketches/sketch2.sm4fg: sketch2.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch2.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch3.om4fg.dep
package/lib/lib/sketches/sketch3.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch3.om4fg: | .interfaces
package/lib/lib/sketches/sketch3.om4fg: sketch3.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch3.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch3.sm4fg: | .interfaces
package/lib/lib/sketches/sketch3.sm4fg: sketch3.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch3.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch4.om4fg.dep
package/lib/lib/sketches/sketch4.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch4.om4fg: | .interfaces
package/lib/lib/sketches/sketch4.om4fg: sketch4.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch4.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch4.sm4fg: | .interfaces
package/lib/lib/sketches/sketch4.sm4fg: sketch4.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch4.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch5.om4fg.dep
package/lib/lib/sketches/sketch5.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch5.om4fg: | .interfaces
package/lib/lib/sketches/sketch5.om4fg: sketch5.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch5.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch5.sm4fg: | .interfaces
package/lib/lib/sketches/sketch5.sm4fg: sketch5.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch5.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch6.om4fg.dep
package/lib/lib/sketches/sketch6.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch6.om4fg: | .interfaces
package/lib/lib/sketches/sketch6.om4fg: sketch6.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch6.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch6.sm4fg: | .interfaces
package/lib/lib/sketches/sketch6.sm4fg: sketch6.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch6.sm4fg: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch7.om4fg.dep
package/lib/lib/sketches/sketch7.om4fg.dep: ;
endif

package/lib/lib/sketches/sketch7.om4fg: | .interfaces
package/lib/lib/sketches/sketch7.om4fg: sketch7.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch7.om4fg: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch7.sm4fg: | .interfaces
package/lib/lib/sketches/sketch7.sm4fg: sketch7.cpp lib/sketches.am4fg.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4fg -S $< ...
	$(gnu.targets.arm.M4F.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4F -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch7.sm4fg: export LD_LIBRARY_PATH=

clean,m4fg ::
	-$(RM) package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg
	-$(RM) package/lib/lib/sketches/GLCDI2C.om4fg
	-$(RM) package/lib/lib/sketches/mon.om4fg
	-$(RM) package/lib/lib/sketches/monitor1.om4fg
	-$(RM) package/lib/lib/sketches/monitor.om4fg
	-$(RM) package/lib/lib/sketches/sketch0.om4fg
	-$(RM) package/lib/lib/sketches/sketch1.om4fg
	-$(RM) package/lib/lib/sketches/sketch2.om4fg
	-$(RM) package/lib/lib/sketches/sketch3.om4fg
	-$(RM) package/lib/lib/sketches/sketch4.om4fg
	-$(RM) package/lib/lib/sketches/sketch5.om4fg
	-$(RM) package/lib/lib/sketches/sketch6.om4fg
	-$(RM) package/lib/lib/sketches/sketch7.om4fg
	-$(RM) package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4fg
	-$(RM) package/lib/lib/sketches/GLCDI2C.sm4fg
	-$(RM) package/lib/lib/sketches/mon.sm4fg
	-$(RM) package/lib/lib/sketches/monitor1.sm4fg
	-$(RM) package/lib/lib/sketches/monitor.sm4fg
	-$(RM) package/lib/lib/sketches/sketch0.sm4fg
	-$(RM) package/lib/lib/sketches/sketch1.sm4fg
	-$(RM) package/lib/lib/sketches/sketch2.sm4fg
	-$(RM) package/lib/lib/sketches/sketch3.sm4fg
	-$(RM) package/lib/lib/sketches/sketch4.sm4fg
	-$(RM) package/lib/lib/sketches/sketch5.sm4fg
	-$(RM) package/lib/lib/sketches/sketch6.sm4fg
	-$(RM) package/lib/lib/sketches/sketch7.sm4fg

lib/sketches.am4fg: package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4fg package/lib/lib/sketches/GLCDI2C.om4fg package/lib/lib/sketches/mon.om4fg package/lib/lib/sketches/monitor1.om4fg package/lib/lib/sketches/monitor.om4fg package/lib/lib/sketches/sketch0.om4fg package/lib/lib/sketches/sketch1.om4fg package/lib/lib/sketches/sketch2.om4fg package/lib/lib/sketches/sketch3.om4fg package/lib/lib/sketches/sketch4.om4fg package/lib/lib/sketches/sketch5.om4fg package/lib/lib/sketches/sketch6.om4fg package/lib/lib/sketches/sketch7.om4fg lib/sketches.am4fg.mak

clean::
	-$(RM) lib/sketches.am4fg.mak
