#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4{1,0,4.9,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g.dep
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g.dep: ;
endif

package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g: | .interfaces
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g: package/package_ti.runtime.wiring.cc32xx.tests.alan.c lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4g: | .interfaces
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4g: package/package_ti.runtime.wiring.cc32xx.tests.alan.c lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/GLCDI2C.om4g.dep
package/lib/lib/sketches/GLCDI2C.om4g.dep: ;
endif

package/lib/lib/sketches/GLCDI2C.om4g: | .interfaces
package/lib/lib/sketches/GLCDI2C.om4g: GLCDI2C.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/GLCDI2C.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/GLCDI2C.sm4g: | .interfaces
package/lib/lib/sketches/GLCDI2C.sm4g: GLCDI2C.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/GLCDI2C.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/monitor1.om4g.dep
package/lib/lib/sketches/monitor1.om4g.dep: ;
endif

package/lib/lib/sketches/monitor1.om4g: | .interfaces
package/lib/lib/sketches/monitor1.om4g: monitor1.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor1.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/monitor1.sm4g: | .interfaces
package/lib/lib/sketches/monitor1.sm4g: monitor1.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor1.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/monitor.om4g.dep
package/lib/lib/sketches/monitor.om4g.dep: ;
endif

package/lib/lib/sketches/monitor.om4g: | .interfaces
package/lib/lib/sketches/monitor.om4g: monitor.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/monitor.sm4g: | .interfaces
package/lib/lib/sketches/monitor.sm4g: monitor.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/mon.om4g.dep
package/lib/lib/sketches/mon.om4g.dep: ;
endif

package/lib/lib/sketches/mon.om4g: | .interfaces
package/lib/lib/sketches/mon.om4g: mon.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/mon.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/mon.sm4g: | .interfaces
package/lib/lib/sketches/mon.sm4g: mon.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/mon.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch0.om4g.dep
package/lib/lib/sketches/sketch0.om4g.dep: ;
endif

package/lib/lib/sketches/sketch0.om4g: | .interfaces
package/lib/lib/sketches/sketch0.om4g: sketch0.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch0.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch0.sm4g: | .interfaces
package/lib/lib/sketches/sketch0.sm4g: sketch0.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch0.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch1.om4g.dep
package/lib/lib/sketches/sketch1.om4g.dep: ;
endif

package/lib/lib/sketches/sketch1.om4g: | .interfaces
package/lib/lib/sketches/sketch1.om4g: sketch1.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch1.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch1.sm4g: | .interfaces
package/lib/lib/sketches/sketch1.sm4g: sketch1.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch1.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch2.om4g.dep
package/lib/lib/sketches/sketch2.om4g.dep: ;
endif

package/lib/lib/sketches/sketch2.om4g: | .interfaces
package/lib/lib/sketches/sketch2.om4g: sketch2.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch2.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch2.sm4g: | .interfaces
package/lib/lib/sketches/sketch2.sm4g: sketch2.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch2.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch3.om4g.dep
package/lib/lib/sketches/sketch3.om4g.dep: ;
endif

package/lib/lib/sketches/sketch3.om4g: | .interfaces
package/lib/lib/sketches/sketch3.om4g: sketch3.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch3.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch3.sm4g: | .interfaces
package/lib/lib/sketches/sketch3.sm4g: sketch3.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch3.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch4.om4g.dep
package/lib/lib/sketches/sketch4.om4g.dep: ;
endif

package/lib/lib/sketches/sketch4.om4g: | .interfaces
package/lib/lib/sketches/sketch4.om4g: sketch4.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch4.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch4.sm4g: | .interfaces
package/lib/lib/sketches/sketch4.sm4g: sketch4.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch4.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch5.om4g.dep
package/lib/lib/sketches/sketch5.om4g.dep: ;
endif

package/lib/lib/sketches/sketch5.om4g: | .interfaces
package/lib/lib/sketches/sketch5.om4g: sketch5.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch5.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch5.sm4g: | .interfaces
package/lib/lib/sketches/sketch5.sm4g: sketch5.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch5.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch6.om4g.dep
package/lib/lib/sketches/sketch6.om4g.dep: ;
endif

package/lib/lib/sketches/sketch6.om4g: | .interfaces
package/lib/lib/sketches/sketch6.om4g: sketch6.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch6.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch6.sm4g: | .interfaces
package/lib/lib/sketches/sketch6.sm4g: sketch6.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch6.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch7.om4g.dep
package/lib/lib/sketches/sketch7.om4g.dep: ;
endif

package/lib/lib/sketches/sketch7.om4g: | .interfaces
package/lib/lib/sketches/sketch7.om4g: sketch7.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I/db/vtree/library/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include  -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch7.om4g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch7.sm4g: | .interfaces
package/lib/lib/sketches/sketch7.sm4g: sketch7.cpp lib/sketches.am4g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC3220S_LAUNCHXL -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -Os  -fno-rtti -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/driverlib" -I"/home/xlibrary/trees/mcpi/mcpi-b19/exports/coresdk_cc32xx_3_01_01_19/source/ti/devices/cc32xx/inc" -I""  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch7.sm4g: export LD_LIBRARY_PATH=

clean,m4g ::
	-$(RM) package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g
	-$(RM) package/lib/lib/sketches/GLCDI2C.om4g
	-$(RM) package/lib/lib/sketches/monitor1.om4g
	-$(RM) package/lib/lib/sketches/monitor.om4g
	-$(RM) package/lib/lib/sketches/mon.om4g
	-$(RM) package/lib/lib/sketches/sketch0.om4g
	-$(RM) package/lib/lib/sketches/sketch1.om4g
	-$(RM) package/lib/lib/sketches/sketch2.om4g
	-$(RM) package/lib/lib/sketches/sketch3.om4g
	-$(RM) package/lib/lib/sketches/sketch4.om4g
	-$(RM) package/lib/lib/sketches/sketch5.om4g
	-$(RM) package/lib/lib/sketches/sketch6.om4g
	-$(RM) package/lib/lib/sketches/sketch7.om4g
	-$(RM) package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.sm4g
	-$(RM) package/lib/lib/sketches/GLCDI2C.sm4g
	-$(RM) package/lib/lib/sketches/monitor1.sm4g
	-$(RM) package/lib/lib/sketches/monitor.sm4g
	-$(RM) package/lib/lib/sketches/mon.sm4g
	-$(RM) package/lib/lib/sketches/sketch0.sm4g
	-$(RM) package/lib/lib/sketches/sketch1.sm4g
	-$(RM) package/lib/lib/sketches/sketch2.sm4g
	-$(RM) package/lib/lib/sketches/sketch3.sm4g
	-$(RM) package/lib/lib/sketches/sketch4.sm4g
	-$(RM) package/lib/lib/sketches/sketch5.sm4g
	-$(RM) package/lib/lib/sketches/sketch6.sm4g
	-$(RM) package/lib/lib/sketches/sketch7.sm4g

lib/sketches.am4g: package/lib/lib/sketches/package/package_ti.runtime.wiring.cc32xx.tests.alan.om4g package/lib/lib/sketches/GLCDI2C.om4g package/lib/lib/sketches/monitor1.om4g package/lib/lib/sketches/monitor.om4g package/lib/lib/sketches/mon.om4g package/lib/lib/sketches/sketch0.om4g package/lib/lib/sketches/sketch1.om4g package/lib/lib/sketches/sketch2.om4g package/lib/lib/sketches/sketch3.om4g package/lib/lib/sketches/sketch4.om4g package/lib/lib/sketches/sketch5.om4g package/lib/lib/sketches/sketch6.om4g package/lib/lib/sketches/sketch7.om4g lib/sketches.am4g.mak

clean::
	-$(RM) lib/sketches.am4g.mak
